baseURL = "https://antoinedw.fr/"
languageCode = "fr-fr"
title = "antoinedw.fr"
theme = "hugo-noir"

defaultContentLanguage = "fr"
defaultContentLanguageInSubdir = true

[languages]
  [languages.fr]
    languageName = "Français"
    title = "antoinedw.fr"
    weight = 1
    contentDir = "content/fr"
    [languages.fr.menu]
      [[languages.fr.menu.main]]
        name = "À propos"
        pageRef = "/about"
        weight = 1
      [[languages.fr.menu.main]]
        name = "Expérience"
        pageRef = "/experience"
        weight = 2
      [[languages.fr.menu.main]]
        name = "Blog"
        pageRef = "/blogs" # Assumes a section named 'blogs'
        weight = 3
      [[languages.fr.menu.main]]
        name = "Contact"
        pageRef = "/contact"
        weight = 4

  [languages.en]
    languageName = "English"
    title = "antoinedw.fr"
    weight = 2
    contentDir = "content/en"
    [languages.en.menu]
      [[languages.en.menu.main]]
        name = "About"
        pageRef = "/about" # Corresponds to content/en/about.md or content/en/about/_index.md
        weight = 1
      [[languages.en.menu.main]]
        name = "Experience"
        pageRef = "/experience"
        weight = 2
      [[languages.en.menu.main]]
        name = "Blog"
        pageRef = "/blogs" # Assumes a section named 'blogs'
        weight = 3
      [[languages.en.menu.main]]
        name = "Contact"
        pageRef = "/contact"
        weight = 4

