baseURL = "https://antoinedw.fr/"
languageCode = "fr-fr"
title = "antoinedw.fr"
theme = "hugo-noir"

defaultContentLanguage = "fr"
defaultContentLanguageInSubdir = true

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

[params]
  math = true

[languages]
  [languages.fr]
    languageName = "Français"
    title = "antoinedw.fr"
    weight = 1
    contentDir = "content/fr"
    [languages.fr.menu]
      [[languages.fr.menu.main]]
        name = "Blog"
        url = "/fr/blog"
        weight = 1
      [[languages.fr.menu.main]]
        name = "Expériences"
        url = "/fr/#experience"
        weight = 2
      [[languages.fr.menu.main]]
        name = "Formations"
        url = "/fr/#education"
        weight = 3

  [languages.en]
    languageName = "English"
    title = "antoinedw.fr"
    weight = 2
    contentDir = "content/en"
    [languages.en.menu]
      [[languages.en.menu.main]]
        name = "Blog"
        url = "/en/blog"
        weight = 1
      [[languages.en.menu.main]]
        name = "Experience"
        url = "/en/#experience"
        weight = 2
      [[languages.en.menu.main]]
        name = "Education"
        url = "/en/#education"
        weight = 3
